# -*- coding: utf-8 -*-
"""Main_Program.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aU8l6SL7I9-RQ6h7iWH2-0hkHxrqAIbV
"""

from super_cashier import Transaction

user = Transaction()
# Test Case 1
# Add Item 1
print("Test Case 1")
print("-----------")
user.add_item("Sampo", 2, 20_000)
print("\n")
# Add Item 2
user.add_item("Pasta Gigi", 3, 15_000)
print("\n")
print("Order Table :")
user.check_order()
user.total_price()

# Test Case 2
# Delete pasta gigi from order table
print("\n")
print("Test Case 2")
print("-----------")
user.delete_item("Pasta Gigi")
print("Order Table :")
user.check_order()
user.total_price()

# Test Case 3
# Reset all transaction
print("\n")
print("Test Case 3")
print("-----------")
user.reset_transaction()

# Test Case 4
print("\n")
print("Test Case 4")
print("-----------")
# Add Item 1
user.add_item("Sampo", 2, 20_000)
print("\n")
# Add Item 2
user.add_item("Pasta Gigi", 3, 15_000)
print("\n")
# Add Item 3
user.add_item("Detergen", 1, 200_000)
print("\n")
# Add Item 4
user.add_item("Mie Instan", 5, 3_000)
print("\n")
print("Order Table :")
user.check_order()
user.total_price()

# Test Case 5
# Update Item, JumlahBarang, dan Harga
print("\n")
print("Test Case 5")
print("-----------")
print("Order Table Before:")
user.check_order()
user.total_price()
print("\n")
# Update Item pasta gigi
user.update_item_name("Pasta Gigi", "Sabun Mandi")
# Update JumlahBarang sampo
user.update_item_quantity("Sampo", 3)
# Update Harga mie instan
user.update_item_price("Mie Instan", 3_500)
print("\n")
print("Order Table After:")
user.check_order()
user.total_price()